// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCil8n9nfKCG8NTvOH1rjihJe1iAl0-EVc',
    appId: '1:341233396669:web:329a83cc25febf2d6b00d4',
    messagingSenderId: '341233396669',
    projectId: 'expense-tracker-9a055',
    authDomain: 'expense-tracker-9a055.firebaseapp.com',
    storageBucket: 'expense-tracker-9a055.firebasestorage.app',
    measurementId: 'G-91YPL7DFF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQemhYpDTurAfEmZvGL-0ajwszAwdo57M',
    appId: '1:341233396669:android:df8e4ac90b9691286b00d4',
    messagingSenderId: '341233396669',
    projectId: 'expense-tracker-9a055',
    storageBucket: 'expense-tracker-9a055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwegGAuJmY0AvrWODtJqnoIPx0j00UN2s',
    appId: '1:341233396669:ios:5ded392fcf0033656b00d4',
    messagingSenderId: '341233396669',
    projectId: 'expense-tracker-9a055',
    storageBucket: 'expense-tracker-9a055.firebasestorage.app',
    iosBundleId: 'com.abraar.expenseFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwegGAuJmY0AvrWODtJqnoIPx0j00UN2s',
    appId: '1:341233396669:ios:5ded392fcf0033656b00d4',
    messagingSenderId: '341233396669',
    projectId: 'expense-tracker-9a055',
    storageBucket: 'expense-tracker-9a055.firebasestorage.app',
    iosBundleId: 'com.abraar.expenseFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCil8n9nfKCG8NTvOH1rjihJe1iAl0-EVc',
    appId: '1:341233396669:web:b9a6ca5dd192f5266b00d4',
    messagingSenderId: '341233396669',
    projectId: 'expense-tracker-9a055',
    authDomain: 'expense-tracker-9a055.firebaseapp.com',
    storageBucket: 'expense-tracker-9a055.firebasestorage.app',
    measurementId: 'G-MR304RVK4K',
  );
}
