name: Flutter CI

on:
  push:
    branches:
      - feature/expense-tracker-ci-cd

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Repository downloaded successfully!"
